### ISSUE TITLE
More number of contributions are added to batch than what it shows during creation of batch

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#11]
@mattwire When created this batch, 1 donation was shown as eligible. 

<img width="592" alt="Screenshot 2020-04-13 at 16 00 24" src="https://user-images.githubusercontent.com/5366545/79131470-923e0980-7da0-11ea-86ea-6a115e09ee04.png">

However, when try to validate, there are seemingly 42 donations were added to the batch. It appears that these are the donation associated with the some financial types disabled.

<img width="1138" alt="Screenshot 2020-04-13 at 16 01 24" src="https://user-images.githubusercontent.com/5366545/79131471-92d6a000-7da0-11ea-9c23-308009106109.png">

**Comment by mattwire** [comment]
@tapashdatta Please can you test with 3.3.6?

**Comment by tapashdatta** [comment]
@mattwire It seems to be adding correct number of donations.  However  the reason for rejection is all messed up. Despite financial types disabled, they were included in the batch. Some of the donation marked as NO also included.  connected to https://github.com/mattwire/uk.co.compucorp.civicrm.giftaid/issues/7
https://github.com/mattwire/uk.co.compucorp.civicrm.giftaid/issues/12

**Comment by mattwire** [comment]
@tapash Please test with 3.3.7 - and enable the "detail" column on the report which will give you more information why they are failing.

**Comment by tapashdatta** [comment]
@mattwire Details column shows, "Empty address; Postcode invalid"
I have removed the address, re add them, and it's CORRECT address. but still showing same message..

**Comment by tapashdatta** [comment]
solved
