### ISSUE TITLE
False positive Address Invalid and cannot submit

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#12]
Although these donors have a valid address in profile and in declaration, despite editing the address, re-saving the donation or creating new declaration these donation still shows validation error. Unless removed from the batch there was no way to proceed with this claim. Cannot find any way to troubleshoot. 

<img width="461" alt="Screenshot 2020-04-13 at 18 28 22" src="https://user-images.githubusercontent.com/5366545/79143521-46e22600-7db5-11ea-992a-992603af2071.png">

**Comment by mattwire** [comment]
@tapashdatta Do these contacts have multiple declarations? The address will be pulled from the declaration that overlaps the date of the contribution. Please also try 3.3.7 which allows you to amend the address on the declaration.

**Comment by tapashdatta** [comment]
@mattwire These contacts does NOT have multiple declaration. And I have tried updating them manually with 3.3.7 editing function. but doesn't seem to made any difference.

**Comment by tapashdatta** [comment]
solved
