### ISSUE TITLE
"Remove From Batch" Link doesn't remove all contribution from batch

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#13]
<img width="836" alt="Screenshot 2020-04-16 at 16 25 42" src="https://user-images.githubusercontent.com/5366545/79474921-f1995500-7ffe-11ea-96f7-80a976c778df.png">

@mattwire  This person had 2 donation in this batch which was rejected, although declaration is fine, financial types are eligible and donations are also marked "Yes". 

When clicked "Remove from batch", only 1 donation was removed from the batch and the other one could not remove despite multiple attempt.

When retried to include those donation into another batch none of them were included

<img width="1138" alt="Screenshot 2020-04-16 at 16 30 05" src="https://user-images.githubusercontent.com/5366545/79475637-da0e9c00-7fff-11ea-93e1-6026bbe60cd5.png">

**Comment by mattwire** [comment]
@tapashdatta Was the batch already submitted?

**Comment by tapashdatta** [comment]
@mattwire No, This was a newly created one and not submitted.

**Comment by tapashdatta** [comment]
@mattwire Sorry, It was actually from a submitted batch.

**Comment by tapashdatta** [comment]
Solved. Thanks.
