### ISSUE TITLE
Donations included in the batch which should not be included!

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#2]
Here is my test donation:
1. By an Organisation
2. Donation was marked as YES eligible for giftaid
3. No giftaid declaration attached to contact profile
4. Financial type is enabled for giftaid settings

I think since there's No giftaid declaration attached to contact profile, & its given by an organisation it should not be eligible for giftaid.

**Comment by mattwire** [comment]
@tapashdatta I can't reproduce this on master - can you update to 3.3 and test again?

**Comment by tapashdatta** [comment]
@mattwire Seems to have fixed in 3.3 branch.
