### ISSUE TITLE
v 3.3.11 breaks "Validate" function of Online Submission Link

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#22]
<img width="484" alt="Screenshot 2020-05-13 at 16 57 25" src="https://user-images.githubusercontent.com/5366545/81836027-d442a280-953a-11ea-97ba-8a9d44007c25.png">

**Comment by mattwire** [comment]
@tapashdatta Please can you test 1.8.4 of giftaidonline - I forgot to tag the release..

**Comment by tapashdatta** [comment]
worked. Thanks
