### ISSUE TITLE
PHP Warning when adding to batch

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#3]
> Warning: Invalid argument supplied for foreach() in CRM_Civigiftaid_Utils_GiftAid::isContributionEligible() (line 533 of /home/webadmin/public_html/cmm-uat/sites/default/files/civicrm/ext/uk.co.compucorp.civicrm.giftaid/CRM/Civigiftaid/Utils/GiftAid.php).
--

Seeing hundreds of errors with branch 3.3 when adding donation to batch.

**Comment by mattwire** [comment]
I think that's resolved in master?
