### ISSUE TITLE
"Yes, and for donations made in the past 4 years" Gets rejected by HMRC

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#4]
@mattwire When donors selects "Yes, and for donations made in the past 4 years" ,  those donations gets rejected by HMRC when submitted with "Giftaid Online" extension.  When submitted online receiving this message " Invalid donor data : Address Data" although the address data is fine.
Also those donations that were rejected, I am not able to add to a new batch again for resubmission.

**Comment by mattwire** [comment]
Fixed via https://github.com/mattwire/uk.co.vedaconsulting.module.giftaidonline/releases/tag/1.8
