### ISSUE TITLE
Recurring (subsequent) contribution is not included in batch

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#6]
When someone donates a recurring contribution, the initial donation gets marked with a first batch and added. 

But the subsequent, donation also gets marked as initial "Batch" ID.  and  donation does not gets included in the new batch. Here's some screenshot of this instances. 

<img width="1345" alt="Screenshot 2019-12-30 at 01 30 12" src="https://user-images.githubusercontent.com/5366545/71565214-62465100-2aa4-11ea-9487-19d1561efbc0.png">
<img width="534" alt="Screenshot 2019-12-30 at 01 32 41" src="https://user-images.githubusercontent.com/5366545/71565215-66726e80-2aa4-11ea-9fe7-3ddebfff9385.png">
<img width="541" alt="Screenshot 2019-12-30 at 01 32 23" src="https://user-images.githubusercontent.com/5366545/71565216-670b0500-2aa4-11ea-8b34-6a5be60fa347.png">
<img width="610" alt="Screenshot 2019-12-30 at 01 31 47" src="https://user-images.githubusercontent.com/5366545/71565217-670b0500-2aa4-11ea-8b98-c84b6bc94885.png">

**Comment by tapashdatta** [comment]
Although December payment states that it was included in batch 54, but that batch was submitted in October, so December payment cannot be included there.

**Comment by mattwire** [comment]
This is because of this line: https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L2646       `CRM_Contribute_BAO_ContributionRecur::copyCustomValues($contributionParams['contribution_recur_id'], $contribution->id);`

See https://github.com/civicrm/civicrm-core/pull/17007 for a workaround

**Comment by mattwire** [comment]
Resolved for this extension via https://github.com/mattwire/uk.co.compucorp.civicrm.giftaid/commit/598d42042c3cd0cf24febdd53ee126f08fbb7697 in 3.3.3
