### ISSUE TITLE
Address & date not updated if declaration existing from previous version

### ISSUE THREAD

**Issue by tapashdatta** [mattwire/uk.co.compucorp.civicrm.giftaid#9]
@mattwire 
I am on 3.3.1 and upgraded to v3.3.3 
When a new declaration is created for a contact who already has a declaration from previous version of extension, the Address & date for current declaration does not update. Also previous declaration does not close.

When deleted all declaration from profile and created new ones, it seems to update as expected.

**Comment by mattwire** [comment]
Please test with 3.3.7

**Comment by tapashdatta** [comment]
Solved. Thanks
